#! /bin/sh

MON_COUNT=$(xrandr --listmonitors | grep  "^ " | wc -l)

if [ $HOST == "archlinux" ]; then
    if [ $MON_COUNT == 2 ]; then
        bspc monitor DP-0 -d I II 
        bspc monitor DP-2 -d III IV
        $HOME/.local/bin/succade -s DP-0 &
        $HOME/.local/bin/succade -s DP-2 &
    else
        bspc monitor -d I II III IV
        $HOME/.local/bin/succade -s edp1 &
    fi    
else
    if [ $MON_COUNT == 2 ]; then
        bspc monitor DP-0 -d I II 
        bspc monitor DP-2 -d III IV
        $HOME/.local/bin/succade -s DP-0 &
        $HOME/.local/bin/succade -s DP-2 &
    elif [ $MON_COUNT == 3 ]; then
        bspc monitor eDP-1 -d I IV 
        bspc monitor DP-1 -d II     
        bspc monitor DP-3 -d III      
        $HOME/.local/bin/succade -s edp1 &
        $HOME/.local/bin/succade -s dp1 &
        $HOME/.local/bin/succade -s dp3 &
    else 
        bspc monitor -d I II III IV
        $HOME/.local/bin/succade -s edp1 &
    fi
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#222222"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='II' focus=on
bspc rule -a TelegramDesktop desktop='III' focus=on follow=on
bspc rule -a 'htop' desktop='IV' focus=on follow=on
bspc rule -a 'mutt' desktop='IV' focus=on follow=on
bspc rule -a 'tasks' desktop='IV' focus=on follow=on
bspc rule -a 'notes' desktop='IV' focus=on follow=on
bspc rule -a 'thunderbird' desktop='IV' focus=on follow=on
bspc rule -a Pavucontrol state=floating floating=on focus=on follow=on
