[env]
WINIT_X11_SCALE_FACTOR = "1"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = '[^ ]+(?:\s*)$' 
command = { program = "tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}", "sh", "-c", "nvim \"$0\""] }
binding = { key = "2", mods = "Control" }

# fc-list : family style | grep Mono 
[font]
size = 20

[font.bold]
#family = "CaskaydiaMono Nerd Font"
#family = "Hurmit Nerd Font"
family = "Monofur Nerd Font"
#family = "M+1Code Nerd Font"
style = "Bold"

[font.normal]
#family = "CaskaydiaMono Nerd Font"
#family = "Hurmit Nerd Font"
#family = "IosevkaTerm Nerd Font"
family = "Monofur Nerd Font"
#family = "M+1Code Nerd Font"
style = "Regular"

[font.italic]
#family = "CaskaydiaMono Nerd Font"
#family = "Hurmit Nerd Font"
family = "Monofur Nerd Font"
style = "Italic"

[window]
opacity = 0.8

# Colors (Nord)
[colors.primary]
background = '0x2E3440'
foreground = '0xD8DEE9'

# Normal colors
[colors.normal]
black =    '0x3B4252'
red =      '0xBF616A'
green =    '0xA3BE8C'
yellow =   '0xEBCB8B'
blue =     '0x81A1C1'
magenta =  '0xB48EAD'
cyan =     '0x88C0D0'
white =    '0xE5E9F0'

# Bright colors
[colors.bright]
black =    '0x4C566A'
red =      '0xBF616A'
green =    '0xA3BE8C'
yellow =   '0xEBCB8B'
blue =     '0x81A1C1'
magenta =  '0xB48EAD'
cyan =     '0x8FBCBB'
white =    '0xECEFF4'
